using System;
using System.Collections.Generic;
using System.Linq;
using CloudflareTray.Models;

namespace CloudflareTray.Services;

/// <summary>What the tray icon shows via the dot in the tunnel.</summary>
public enum TrayStatus
{
    /// <summary>No tunnel active, no dot.</summary>
    Idle,
    /// <summary>At least one tunnel is running, none is reconnecting: green dot.</summary>
    Running,
    /// <summary>At least one tunnel is reconnecting: orange dot.</summary>
    Reconnecting,
}

/// <summary>
/// Picks the matching tray icon from Assets/tray (generated by tools/generate-icons.sh):
/// status via the dot, glyph color matching the panel.
/// </summary>
public static class TrayIconAssets
{
    public static TrayStatus StatusOf(IEnumerable<TunnelState> states)
    {
        var list = states.ToList();
        if (list.Contains(TunnelState.Reconnecting)) return TrayStatus.Reconnecting;
        if (list.Contains(TunnelState.Running)) return TrayStatus.Running;
        return TrayStatus.Idle;
    }

    /// <param name="whiteGlyph">White glyph for dark panels, otherwise black.</param>
    /// <param name="windows">Windows needs an .ico, Linux/macOS get a PNG.</param>
    public static string Uri(TrayStatus status, bool whiteGlyph, bool windows)
    {
        var color = whiteGlyph ? "white" : "black";
        var name = status.ToString().ToLowerInvariant();
        var extension = windows ? "ico" : "png";
        return $"avares://CloudflareTray/Assets/tray/tray-{color}-{name}.{extension}";
    }

    /// <summary>
    /// Whether the panel containing the tray is dark.
    /// Windows: separate setting for the taskbar. GNOME: the top bar is always dark.
    /// Otherwise (KDE, macOS, …): same as the app's color scheme.
    /// </summary>
    public static bool IsTrayBarDark(bool appThemeIsDark)
    {
        if (OperatingSystem.IsWindows())
        {
            // 1 = light taskbar; if the value is missing (older Windows versions), it is dark
            var value = Microsoft.Win32.Registry.GetValue(
                @"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize",
                "SystemUsesLightTheme", 0);
            return value is not 1;
        }

        if (OperatingSystem.IsLinux() && IsGnome(Environment.GetEnvironmentVariable("XDG_CURRENT_DESKTOP")))
            return true;

        return appThemeIsDark;
    }

    /// <summary>XDG_CURRENT_DESKTOP is a list such as "ubuntu:GNOME".</summary>
    public static bool IsGnome(string? currentDesktop) =>
        currentDesktop?.Split(':').Any(d => d.Equals("GNOME", StringComparison.OrdinalIgnoreCase)) == true;

    public static string ToolTip(int total, int running, int reconnecting) => (total, running, reconnecting) switch
    {
        (0, _, _) => "Cloudflare Tunnel Manager – no tunnels",
        (_, _, > 0) => $"Cloudflare Tunnel Manager – {running} of {total} active, {reconnecting} reconnecting",
        _ => $"Cloudflare Tunnel Manager – {running} of {total} active",
    };
}
